name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  push-to-hf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://huggingface.co/spaces/Yadu-sharma/BA-Agentic-AI || true
          git push --force https://user:${HF_TOKEN}@huggingface.co/spaces/Yadu-sharma/BA-Agentic-AI main